### PR TITLE
Improvement title card options

### PR DESCRIPTION
**Pull request by KamiliaBlow**
Closes the issue https://github.com/wrycu/StarWarsFFG-Enhancements/issues/203

Changes: 
- Deleted the file title_cards_dialog.html (it is not used)
- Slightly improved UI for title card input menu
- Added ability to change font color in HEX + settings
- Added customization so you can speed up or slow down the text zoom + settings
- Now if the file path for Logo is missing, you can use the new input fields to display text instead of Logo image + size settings

Problem:
- Need to manually add new localization strings for other languages

### CODE REVIEW

**Comment by wrycu** [comment]
@KamiliaBlow thanks for the PR!

@arknano I don't actually use this feature. Can you please review these changes and provide feedback?

My only note is that it significantly changes the font sizes even fi you don't use the new functionality.

Old format (captured a bit late so the coloring is dumb - ignore that)

image

New format

image

**Comment by KamiliaBlow** [comment]
Given that we can change the text size in the settings, I don't see much of a problem with the basic settings. (The logo suggests long words for the top margin and 1-2 words for the bottom margin. I used "The book of boba fett" as an example)

**Comment by wrycu** [comment]
I don't mean it as a bad thing; just wanted to call it out as a default behavior change. As I said, I personally don't use it.

I'll let @arknano comment when he eventually wakes up.

**Comment by arknano** [comment]
Fantastic stuff, thanks for improving the feature! I did intend all these features but got very lazy once I had the basic part in haha

One tiny improvement I'd suggest is just making it clear in the dialog that the logo text only works if there's no logo defined, it as it's a bit unintuitive to just have some fields that do nothing in certain circumstances! Not a big deal though

I'm ok with the change to defaults after testing it myself, the original defaults were kind of made up to be fair.

**Review by arknano — APPROVED** [review]

**Comment by wrycu** [comment]
Thanks for the review @arknano and thanks for the PR, @KamiliaBlow!

**Pull request merged**
